export { SettingsApiRepository } from "./repositories/SettingsApiRepository";
export {
  crudEndpoints,
  TENANT_ENDPOINTS,
  BRANCH_ENDPOINTS,
  APP_CUSTOMER_ENDPOINTS,
  BRANCH_CUSTOMER_ENDPOINTS,
  SYS_ADMIN_ENDPOINTS,
  METADATA_ENDPOINTS,
  MODULE_ENDPOINTS,
  OPERATION_ENDPOINTS,
  PRODUCT_ENDPOINTS,
  SUBSCRIPTION_ENDPOINTS,
  SETTINGS_ENDPOINTS,
} from "./endpoints/adminEndpoints";
